# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
    ]
