# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_remove_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(default=datetime.datetime(2016, 1, 8, 12, 52, 16, 332374, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
